-- Foreign Keys
START TRANSACTION;
-- EMPLOYEE -> BRANCH (1:M)
ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EMPLOYEE_BRANCH
FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH(BRANCH_ID);

-- MANAGER -> EMPLOYEE (1:1)
ALTER TABLE MANAGER
ADD CONSTRAINT FK_MANAGER_EMPLOYEE
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID);

-- SELLER -> EMPLOYEE (1:1)
ALTER TABLE SELLER
ADD CONSTRAINT FK_SELLER_EMPLOYEE
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID);


-- BOOK -> PUBLISHER (M:1)
ALTER TABLE BOOK
ADD CONSTRAINT FK_BOOK_PUBLISHER
FOREIGN KEY (PBS_ID) REFERENCES PUBLISHER(PBS_ID);

-- BOOK_AUTHOR -> BOOK (M:N)
ALTER TABLE BOOK_AUTHOR
ADD CONSTRAINT FK_BOOKAUTHOR_BOOK
FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID);

-- BOOK_AUTHOR -> AUTHOR (M:N)
ALTER TABLE BOOK_AUTHOR
ADD CONSTRAINT FK_BOOKAUTHOR_AUTHOR
FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID);

-- BOOK_GENRE -> BOOK (M:N)
ALTER TABLE BOOK_GENRE
ADD CONSTRAINT FK_BOOKGENRE_BOOK
FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID);

-- BOOK_GENRE -> GENRE (M:N)
ALTER TABLE BOOK_GENRE
ADD CONSTRAINT FK_BOOKGENRE_GENRE
FOREIGN KEY (GENRE_ID) REFERENCES GENRE(GENRE_ID);

-- ORDER_ITEM -> ORDER (M:N)
ALTER TABLE ORDER_ITEM
ADD CONSTRAINT FK_ORDERITEM_ORDER
FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID);

-- ORDER_ITEM -> BOOK (M:N)
ALTER TABLE ORDER_ITEM
ADD CONSTRAINT FK_ORDERITEM_BOOK
FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID);


-- MEMBERSHIP_CARD -> CUSTOMER (1:1)
ALTER TABLE MEMBERSHIP_CARD
ADD CONSTRAINT FK_MEMBER_CUSTOMER
FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER(CUS_ID);

-- PROMOTION -> BRANCH (M:1)
ALTER TABLE PROMOTION
ADD CONSTRAINT FK_PROMOTION_BRANCH
FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH(BRANCH_ID);

-- POINT -> MEMBERSHIP_CARD (M:1)
ALTER TABLE POINT
ADD CONSTRAINT FK_POINT_MEMBER
FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERSHIP_CARD(MEMBER_ID);

-- ORDER -> CUSTOMER (M:1)
ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDER_CUSTOMER
FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER(CUS_ID);

-- ORDER -> BRANCH (M:1)
ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDER_BRANCH
FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH(BRANCH_ID);

-- RENEWAL -> MEMBERSHIP_CARD (M:1)
ALTER TABLE RENEWAL
ADD CONSTRAINT FK_RENEWAL_MEMBER
FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERSHIP_CARD(MEMBER_ID);

-- RECEIPT -> BRANCH (M:1)
ALTER TABLE RECEIPT
ADD CONSTRAINT FK_RECEIPT_BRANCH
FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH(BRANCH_ID);

-- RECEIPT -> ORDER (1:1)
ALTER TABLE RECEIPT
ADD CONSTRAINT FK_RECEIPT_ORDER
FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID);

COMMIT;