CREATE DATABASE IF NOT EXISTS naiin_bookstore;
use naiin_bookstore;

START TRANSACTION;

CREATE TABLE BRANCH (
    BRANCH_ID INT AUTO_INCREMENT PRIMARY KEY,
    BRANCH_NAME VARCHAR(100),
    BRANCH_PHONE VARCHAR(20),
    BRANCH_EMAIL VARCHAR(100),
    BRANCH_STATE VARCHAR(50),
    BRANCH_COUNTRY VARCHAR(50),
    BRANCH_CITY VARCHAR(50),
    BRANCH_POSTCODE VARCHAR(10)
);

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID INT AUTO_INCREMENT PRIMARY KEY,
    BRANCH_ID INT,
    EMP_FNAME VARCHAR(50),
    EMP_LNAME VARCHAR(50),
    EMP_BDATE DATE,
    EMP_SEX VARCHAR(10),
    EMP_SALARY DECIMAL(10,2),
    EMP_TEL VARCHAR(20),
    EMP_EMAIL VARCHAR(100),
    EMP_WORKHOUR INT,
    EMP_SKILL VARCHAR(100)
);

CREATE TABLE MANAGER (
    EMPLOYEE_ID INT PRIMARY KEY,
    BRANCH_BUDGET DECIMAL(15,2)
);


CREATE TABLE CUSTOMER (
    CUS_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUS_FNAME VARCHAR(50),
    CUS_LNAME VARCHAR(50),
    CUS_TEL VARCHAR(20),
    CUS_SEX VARCHAR(10),
    CUS_EMAIL VARCHAR(100),
    CUS_DISTRICT VARCHAR(50),
    CUS_PROVINCE VARCHAR(50),
    CUS_COUNTRY VARCHAR(50),
    CUS_POSTCODE VARCHAR(10),
    CUS_BDATE DATE
);

CREATE TABLE GENRE (
    GENRE_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50),
    PRODUCTTYPE VARCHAR(50)
);

CREATE TABLE PAYMENT (
    PAY_ID INT AUTO_INCREMENT PRIMARY KEY,
    PAY_METHOD VARCHAR(50),
    PAY_STATUS VARCHAR(20)
);

CREATE TABLE SELLER (
    EMPLOYEE_ID INT PRIMARY KEY,
    TIPS DECIMAL(10,2)
);

CREATE TABLE AUTHOR (
    AUTHOR_ID INT AUTO_INCREMENT PRIMARY KEY,
    AUTHOR_FNAME VARCHAR(50),
    AUTHOR_LNAME VARCHAR(50),
    AUTHOR_PENNAME VARCHAR(50),
    AUTHOR_CONTACT VARCHAR(100)
);

CREATE TABLE PUBLISHER (
    PBS_ID INT AUTO_INCREMENT PRIMARY KEY,
    PBS_NAME VARCHAR(100),
    PBS_DISTRICT VARCHAR(50),
    PBS_PROVINCE VARCHAR(50),
    PBS_COUNTRY VARCHAR(50),
    PBS_POSTCODE VARCHAR(10),
    PBS_EMAIL VARCHAR(100),
    PBS_PHONE VARCHAR(20)
);

CREATE TABLE BOOK (
    BOOK_ID INT AUTO_INCREMENT PRIMARY KEY,
    PBS_ID INT,
    BOOK_TITLE VARCHAR(200),
    BOOK_ISBN VARCHAR(20),
    BOOK_PRICE DECIMAL(10,2),
    BOOK_IMAGE VARCHAR(255),
    BOOK_PAGE INT
);

-- Junction Table: BOOK_AUTHOR (M:N)
CREATE TABLE BOOK_AUTHOR (
    BOOK_ID INT,
    AUTHOR_ID INT,
    PRIMARY KEY (BOOK_ID, AUTHOR_ID)
);

-- Junction Table: BOOK_GENRE (M:N)
CREATE TABLE BOOK_GENRE (
    BOOK_ID INT,
    GENRE_ID INT,
    PRIMARY KEY (BOOK_ID, GENRE_ID)
);

CREATE TABLE MEMBERSHIP_CARD (
    MEMBER_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUS_ID INT,
    MEMBER_APPLY_DATE DATE,
    MEMBER_EXP_DATE DATE,
    MEMBER_POINTBALANCE DECIMAL(10,2),
    MEMBER_TOTALDAY INT
);

CREATE TABLE PROMOTION (
    PRO_ID INT AUTO_INCREMENT PRIMARY KEY,
    BRANCH_ID INT,
    PRO_START_DATE DATE,
    PRO_END_DATE DATE,
    PRO_NAME VARCHAR(100),
    PRO_DISCOUNTRATE DECIMAL(5,2)
);

CREATE TABLE POINT (
    POINT_ID INT AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID INT,
    EARN_DATE DATE,
    EXPIRY_DATE DATE,
    POINT_AMOUNT INT
);

CREATE TABLE ORDERS (
    ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUS_ID INT,
    BRANCH_ID INT,
    ORDER_GRANDTOTAL DECIMAL(10,2),
    ORDER_DATE DATE
);

-- Junction Table: ORDER_ITEM (M:N; ORDER <--> BOOK)
CREATE TABLE ORDER_ITEM (
    ORDER_ID INT,
    BOOK_ID INT,
    QUANTITY INT,
    PRICE DECIMAL(10,2), -- Price at time of purchase (may differ from BOOK_PRICE due to promotions)
    PRIMARY KEY (ORDER_ID, BOOK_ID)
);

CREATE TABLE RENEWAL (
    RENEWAL_ID INT AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID INT,
    RENEWAL_DATE DATE,
    RENEWAL_FEE DECIMAL(10,2)
);

-- ตาราง RECEIPT
CREATE TABLE RECEIPT (
    RC_NO INT AUTO_INCREMENT PRIMARY KEY,
    BRANCH_ID INT,
    ORDER_ID INT,
    RC_CO_TAXID VARCHAR(20),
    RC_DATE DATE,
    RC_TAX_AMOUNT DECIMAL(10,2),
    RC_VAT_AMOUNT DECIMAL(10,2),
    RC_GRANDTOTAL DECIMAL(10,2)
);

COMMIT;